# Generated by Django 3.1.2 on 2020-10-29 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=70)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=70)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=70)),
                ('price_full', models.IntegerField(blank=True, default=0)),
                ('price_per_month', models.IntegerField(blank=True, default=0)),
                ('description_full', models.TextField(blank=True)),
                ('description_short', models.TextField(blank=True)),
                ('program_length', models.IntegerField(blank=True, default=0)),
                ('academic_hours', models.IntegerField(blank=True, default=0)),
                ('start_date', models.DateField(blank=True)),
                ('format', models.TextField(blank=True)),
                ('specials', models.TextField(blank=True)),
                ('p_code', models.CharField(blank=True, max_length=100)),
                ('main_image', models.ImageField(blank=True, upload_to='course_photos/%Y/%m/%d/')),
                ('is_free', models.BooleanField(default=False)),
                ('course_published', models.BooleanField(default=True)),
                ('link_to_product', models.URLField(blank=True, max_length=1000)),
                ('direction_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.vendor')),
            ],
        ),
    ]
