# Generated by Django 3.1.2 on 2020-10-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20201030_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='russian_alias',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
