# Generated by Django 3.1.2 on 2020-11-01 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20201031_2351'),
    ]

    operations = [
    ]
