# Generated by Django 3.1.2 on 2020-11-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20201103_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
