# Generated by Django 3.1.2 on 2020-11-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_vendorcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='start_date',
            field=models.DateField(blank=True, default=0),
        ),
    ]
