# Generated by Django 3.1.2 on 2020-12-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_listing_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='rating',
        ),
    ]
