# Generated by Django 3.1.2 on 2020-11-01 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201102_0032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyRating',
        ),
    ]
